import './tags/tiff-ifd0-values.js'
import './tags/tiff-gps-keys.js'
import './tags/tiff-exif-keys.js'
import './tags/tiff-exif-values.js'
import './tags/icc-keys.js'
import './tags/icc-values.js'
import './tags/iptc.js'
export * from './index-lite.js'