import './tags/tiff-ifd0-values.js'
import './tags/tiff-gps-tags.js'
import './tags/tiff-exif-tags.js'
import './tags/tiff-exif-values.js'
import './tags/icc-tags.js'
import './tags/icc-values.js'
import './tags/iptc.js'
export * from './index-lite.js'